image: mcr.microsoft.com/dotnet/sdk:6.0
build-and-test:
  stage: test
  variables:
    GIT_STRATEGY: clone
  script:
    - 'dotnet clean'
    - 'dotnet build'
    - 'dotnet test --logger:"junit;MethodFormat=Class;FailureBodyFormat=Verbose"'
  artifacts:
    when: always
    reports:
      junit:
        - ./**/TestResults.xml
